// Memory.styles.js

// ... (estilos de memoryCardStyles e memoryGalleryStyles que você já tem) ...

export const memoryCardStyles = {
  card: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    display: 'flex',
    flexDirection: 'column',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    cursor: 'pointer',
    position: 'relative',
    border: '1px solid #f0f0f0',
  },
  cardHover: {
    transform: 'translateY(-4px)',
    boxShadow: '0 12px 24px rgba(0,0,0,0.15)',
    borderColor: '#1B7A9B',
  },
  imageContainer: {
    backgroundColor: '#f0f2f5',
    height: '200px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    position: 'relative',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.3s ease',
  },
  imageHover: {
    transform: 'scale(1.05)',
  },
  content: {
    padding: '20px',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  title: {
    margin: 0,
    color: '#1B7A9B',
    fontSize: '1.25rem',
    fontWeight: '600',
    lineHeight: '1.3',
  },
  description: {
    margin: 0,
    fontSize: '0.95rem',
    color: '#666',
    lineHeight: '1.5',
    flex: 1,
  },
  date: {
    color: '#999',
    fontSize: '0.85rem',
    fontWeight: '500',
    marginTop: 'auto',
  },
  badge: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    backgroundColor: 'rgba(255,255,255,0.9)',
    color: '#1B7A9B',
    padding: '4px 8px',
    borderRadius: '12px',
    fontSize: '0.75rem',
    fontWeight: '600',
    backdropFilter: 'blur(4px)',
  },
};

export const memoryGalleryStyles = {
  container: {
    padding: '40px 32px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  header: {
    textAlign: 'center',
    marginBottom: '40px',
  },
  title: {
    fontSize: '2.5rem',
    fontWeight: '700',
    color: '#1B7A9B',
    margin: '0 0 16px 0',
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: '1.1rem',
    color: '#666',
    margin: '0 auto 32px auto',
    maxWidth: '600px',
    lineHeight: '1.6',
  },
  searchContainer: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: '40px',
  },
  searchWrapper: {
    position: 'relative',
    width: '100%',
    maxWidth: '500px',
  },
  searchInput: {
    padding: '16px 24px 16px 48px',
    width: '100%',
    border: '2px solid #e1e5e9',
    borderRadius: '50px',
    fontSize: '1rem',
    outline: 'none',
    transition: 'all 0.3s ease',
    backgroundColor: '#fff',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
  },
  searchInputFocus: {
    borderColor: '#1B7A9B',
    boxShadow: '0 4px 12px rgba(27,122,155,0.15)',
  },
  searchIcon: {
    position: 'absolute',
    left: '16px',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#999',
    fontSize: '1.2rem',
  },
  clearButton: {
    position: 'absolute',
    right: '16px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    color: '#999',
    cursor: 'pointer',
    fontSize: '1.2rem',
    padding: '4px',
    borderRadius: '50%',
    transition: 'all 0.2s ease',
  },
  filters: {
    display: 'flex',
    justifyContent: 'center',
    gap: '12px',
    marginBottom: '32px',
    flexWrap: 'wrap',
  },
  filterButton: {
    padding: '8px 16px',
    border: '2px solid #e1e5e9',
    borderRadius: '20px',
    backgroundColor: '#fff',
    color: '#666',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: '500',
    transition: 'all 0.2s ease',
  },
  filterButtonActive: {
    backgroundColor: '#1B7A9B',
    borderColor: '#1B7A9B',
    color: '#fff',
  },
  gallery: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '24px',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
    color: '#999',
  },
};

// --- NOVOS ESTILOS PARA O MODAL ---
export const memoryModalStyles = {
overlay: {
  position: 'fixed',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(10, 25, 41, 0.7)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1000,
  padding: '20px',
  backdropFilter: 'blur(5px)',
  animation: 'fadeIn 0.3s ease-in-out',
},
content: {
  backgroundColor: '#fff',
  borderRadius: '16px',
  width: '100%',
  maxWidth: '900px',
  maxHeight: '90vh',
  display: 'grid',
  gridTemplateColumns: '1fr', // Layout de coluna única para mobile
  boxShadow: '0 15px 40px rgba(0,0,0,0.25)',
  position: 'relative',
  overflow: 'hidden',
  animation: 'scaleIn 0.4s cubic-bezier(0.165, 0.84, 0.44, 1) forwards',
},
closeButton: {
  position: 'absolute',
  top: '12px',
  right: '12px',
  background: 'rgba(0, 0, 0, 0.3)',
  color: '#fff',
  border: 'none',
  borderRadius: '50%',
  width: '36px',
  height: '36px',
  cursor: 'pointer',
  fontSize: '24px',
  lineHeight: '36px',
  textAlign: 'center',
  zIndex: 10,
  transition: 'background-color 0.2s ease, transform 0.2s ease',
},
imageContainer: {
  width: '100%',
  height: '40vh', // Altura definida para a imagem
  backgroundColor: '#e0e0e0',
  overflow: 'hidden',
},
image: {
  width: '100%',
  height: '100%',
  objectFit: 'cover',
},
details: {
  padding: '24px 32px',
  overflowY: 'auto',
  display: 'flex',
  flexDirection: 'column',
},
badge: {
  backgroundColor: '#1B7A9B',
  color: '#fff',
  padding: '4px 12px',
  borderRadius: '16px',
  fontSize: '0.8rem',
  fontWeight: '600',
  alignSelf: 'flex-start',
  marginBottom: '16px',
},
title: {
  margin: '0 0 12px 0',
  fontSize: '2rem',
  fontWeight: '700',
  color: '#1c3d5a',
},
description: {
  margin: '0 0 24px 0',
  fontSize: '1rem',
  lineHeight: '1.7',
  color: '#555',
  flexGrow: 1,
},
date: {
  color: '#888',
  fontSize: '0.9rem',
  marginTop: 'auto',
  textAlign: 'right',
},
};
