export const memoryStyles = {
  gallery: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '24px',
    padding: '40px 32px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
    display: 'flex',
    flexDirection: 'column',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
  },
  cardHover: {
    transform: 'translateY(-4px)',
    boxShadow: '0 12px 24px rgba(0,0,0,0.15)',
  },
  imageContainer: {
    height: '200px',
    backgroundColor: '#f0f2f5',
    overflow: 'hidden',
  },
  cardImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.3s ease',
  },
  imageHover: {
    transform: 'scale(1.05)',
  },
  cardContent: {
    padding: '20px',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  cardTitle: {
    margin: 0,
    color: '#1B7A9B',
    fontSize: '1.25rem',
  },
  cardDescription: {
    margin: 0,
    fontSize: '0.95rem',
    color: '#666',
    flex: 1,
  },
  cardDate: {
    color: '#999',
    fontSize: '0.85rem',
    marginTop: 'auto',
  },
};

export const formStyles = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 25, 41, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
    backdropFilter: 'blur(5px)',
    animation: 'fadeIn 0.3s ease-in-out',
  },
  content: {
    backgroundColor: '#fff',
    borderRadius: '16px',
    width: '100%',
    maxWidth: '600px',
    padding: '32px 40px',
    boxShadow: '0 15px 40px rgba(0,0,0,0.25)',
    animation: 'scaleIn 0.4s cubic-bezier(0.165, 0.84, 0.44, 1) forwards',
  },
  title: {
    margin: '0 0 32px 0',
    fontSize: '1.8rem',
    textAlign: 'center',
    color: '#1c3d5a',
  },
  inputGroup: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    marginBottom: '8px',
    fontWeight: '600',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    border: '1px solid #ccc',
    borderRadius: '8px',
    fontSize: '1rem',
  },
  textarea: {
    width: '100%',
    padding: '12px 16px',
    border: '1px solid #ccc',
    borderRadius: '8px',
    fontSize: '1rem',
    minHeight: '100px',
  },
  imageUploadLabel: {
    width: '100%',
    height: '150px',
    border: '2px dashed #ccc',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    textAlign: 'center',
    color: '#888',
    marginBottom: '20px',
  },
  imagePreview: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: '10px',
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '32px',
  },
  button: {
    padding: '12px 24px',
    border: 'none',
    borderRadius: '8px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    backgroundColor: '#1B7A9B',
    color: '#fff',
  },
  buttonSecondary: {
    backgroundColor: '#f0f2f5',
    color: '#333',
  },
};

export const memoryModalStyles = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 25, 41, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
    backdropFilter: 'blur(5px)',
    animation: 'fadeIn 0.3s ease-in-out',
  },
  content: {
    backgroundColor: '#fff',
    borderRadius: '16px',
    width: '100%',
    maxWidth: '900px',
    maxHeight: '90vh',
    display: 'grid',
    gridTemplateColumns: '1fr',
    '@media (min-width: 768px)': {
      gridTemplateColumns: '1fr 1fr',
    },
    boxShadow: '0 15px 40px rgba(0,0,0,0.25)',
    position: 'relative',
    overflow: 'hidden',
    animation: 'scaleIn 0.4s cubic-bezier(0.165, 0.84, 0.44, 1) forwards',
  },
  closeButton: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    background: 'rgba(0, 0, 0, 0.3)',
    color: '#fff',
    border: 'none',
    borderRadius: '50%',
    width: '36px',
    height: '36px',
    cursor: 'pointer',
    fontSize: '24px',
    lineHeight: '36px',
    zIndex: 10,
    transition: 'all 0.2s ease',
  },
  imageContainer: {
    width: '100%',
    height: '40vh',
    minHeight: '300px',
    backgroundColor: '#e0e0e0',
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  details: {
    padding: '24px 32px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
  },
  badge: {
    backgroundColor: '#1B7A9B',
    color: '#fff',
    padding: '4px 12px',
    borderRadius: '16px',
    fontSize: '0.8rem',
    fontWeight: '600',
    alignSelf: 'flex-start',
    marginBottom: '16px',
  },
  modalTitle: {
    margin: '0 0 12px 0',
    fontSize: '2rem',
    fontWeight: '700',
    color: '#1c3d5a',
  },
  description: {
    margin: '0 0 24px 0',
    fontSize: '1rem',
    lineHeight: '1.7',
    color: '#555',
    flexGrow: 1,
  },
  date: {
    color: '#888',
    fontSize: '0.9rem',
    marginTop: 'auto',
    textAlign: 'right',
  },
};